name = "chickenroad-predictor-app-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=chickenroad-predictor-app.com"
HMAC_KEY = "6b62cbd337c98238a906729c0ed6c86d1e506645ed044dae3044eab6467e9268"
COOKIE_NAME = "msc"
PLAY_PATH = "explore"
BUTTON_ID = "p37afdf2561ec90cd910ae0dd73eab2e9"
GATE_SALT = "0c8897295818f4d7"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0by4"
CTA_SELECTOR = ".play-button"
